general:
  focus_follows_cursor: false
  cursor_follows_focus: true
  toggle_workspace_on_refocus: true
  show_floating_on_top: true
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: "false"

gaps:
  inner_gap: "2px"
  outer_gap: "2px"

focus_borders:
  active:
    enabled: true
    color: "#6523ff"
  inactive:
    enabled: false
    color: "#7a5bc2"

bar:
  enabled: true
  opacity: 0.82
  height: "32px"
  font_family: "RobotoMono Nerd Font Mono"
  font_size: "10px"
  font_weight: "800"
  # offset_x: "10px"
  # offset_y: "2px"
  border_radius: "12px"
  border_width: "2px"
  border_color: "#2c1943"
  padding: "1px 0 1px 0"
  background: "#141118"
  foreground: "#fcfbf8"

  components_left:
  # - type: "window title"
  #   padding: "3px 8px"
  #   border_radius: "8px"
  #   border_width: "2px"
  #   border_color: "#2e596d"
  #   # font_size: "10px"
  #   font_weight: "400"
  - type: "system tray"
    label_expand_text: "<attr fs='32' fg='#9e7eff'>ÓòÜ</attr>"
    label_collapse_text: "<attr fs='28' fg='#9e7eff'>\U000F0BAB</attr>"
    padding: "6px 6px 6px 0px"
    margin: "0 4px"
    # border_radius: "8px"
    border_width: "0px 2px 0px 0"
    border_color: "#451481"
  - type: "music"
    label_not_playing: "<attr fg='#75c3b6'>\U000F03E4</attr>"
    label_paused: "{song_title} - {artist_name}"
    label_playing: "<attr fg='#75c3b6'>\U000F0F1B {song_title} - {artist_name}</attr>"
    max_title_length: 20
    max_artist_length: 20
    padding: "6px 0"
    margin: "0 4px"
    # border_radius: "8px"
    # border_width: "2px"
    border_color: "#492f55"
  - type: "volume"
    label_low: "<attr fg='#ffa0a0'>\U000F057F {volume_level}%</attr>"
    label_medium: "<attr fg='#ffffa5'>\U000F0580 {volume_level}%</attr>"
    label_high: "<attr fg='#b7ffb7'>\U000F057E {volume_level}%</attr>"
    label_mute: "<attr fg='#a1a1ff'>\U000F075F {volume_level}%</attr>"
    padding: "6px 0"
    margin: "0 4px"
    # border_radius: "8px"
    # border_width: "2px"
    border_color: "#492f55"

  components_center:
  - type: "binding mode"
    padding: "0 10px"
    # border_radius: "8px"
    # border_width: "2px"
    # font_size: "13px"
    border_color: "#2d1096"
  - type: "tiling direction"
    foreground: "#ffbacf"
    label_horizontal: "‚ÆÇ"
    label_vertical: "‚ÆÅ"
    padding: "0 10px"
    # border_radius: "8px"
    # border_width: "2px"
    border_color: "#502961"
  - type: "workspaces"
    font_size: "24px"
    # border_radius: "20px"
    border_width: "3px"
    border_color: "#221949"
    margin: "-10px 2px -10px 0"
    # margin: "-4px 2px"
    focused_workspace_background: "#372359"
    focused_workspace_foreground: "#fffbca"

  components_right:
  - type: "network"
    label_no_internet: "<attr fg='#9f1212'>\U000F0202</attr>"
    label_ethernet: "<attr fg='#50976e'>\U000F0201</attr>"
    padding: "6px 0"
    margin: "0 4px"
  - type: "weather"
    label: "<attr>\U000F07B5</attr> {temp}¬∞C"
    margin: "0 2px 0 0"
    padding: "2px 5px"
    # border_radius: "8px"
    # border_width: "2px"
    border_color: "#3f258d"
    longitude: "6.953101"
    latitude: "50.935173"
    label_sun: "‚òÄÔ∏è {temperature_celsius}¬∞C"
    label_moon: "üåô {temperature_celsius}¬∞C"
    label_cloud_moon: "üåô‚òÅÔ∏è {temperature_celsius}¬∞C"
    label_cloud_sun: "‚õÖ {temperature_celsius}¬∞C"
    label_cloud_moon_rain: "üåôüåßÔ∏è {temperature_celsius}¬∞C"
    label_cloud_sun_rain: "üå¶Ô∏è {temperature_celsius}¬∞C"
    label_cloud_rain: "üåßÔ∏è {temperature_celsius}¬∞C"
    label_snow_flake: "‚ùÑÔ∏è {temperature_celsius}¬∞C"
    label_thunderstorm: "‚ö° {temperature_celsius}¬∞C"
    label_cloud: "‚òÅÔ∏è {temperature_celsius}¬∞C"
  - type: "clock"
    # margin: "0 -8px 0 0"
    padding: "2px"
    # border_radius: "8px"
    # border_width: "2px"
    border_color: "#3f258d"
    time_formatting: "dd.MM.yyyy HH:mm"
  - type: "cpu"
    # margin: "-10px 6px -10px 0"
    padding: "2px 8px"
    # border_radius: "10px"
    border_width: "0px 0px 0px 2px"
    border_color: "#7e2727"
    label: "<attr fs='24'>Ôãõ</attr>|{percent_usage}%"
    font_size: "12px"
    refresh_interval_ms: 1000
  - type: "memory"
    # margin: "-10px 6px -10px 0"
    padding: "2px 8px"
    border_width: "0px 0px 0px 0"
    border_color: "#fffbca"
    label: "<attr fs='24'>ÓøÖ</attr>|{percent_usage}%"
    font_size: "12px"
    refresh_interval_ms: 1000
  - type: "gpu"
    border_radius: "8px"
    # margin: "0 -2px 0 0"
    padding: "2px 8px"
    border_width: "0px 0 0px 0"
    border_color: "#38277e"
    label: "<attr fs='24'>ÔÄΩ</attr>|{percent_usage}%"
    font_size: "12px"
    refresh_interval_ms: 1000

workspaces:
- name: "1"
  display_name: "¬πÔÄï‚óå"
- name: "2"
  display_name: "¬≤ÔÑ°‚óå"
- name: "3"
  display_name: "¬≥Ôââ‚óå"
- name: "4"
  display_name: "‚Å¥ÔÑ≥‚óå"
- name: "5"
  display_name: "‚ÅµÔÇÜ‚óå"
- name: "6"
  display_name: "‚Å∂ÔÜº‚óå"
- name: "7"
  display_name: "‚Å∑Ôâ®‚óå"
- name: "8"

  display_name: "‚Å∏ÔÄì‚óå"
- name: "9"
  display_name: "‚ÅπÔÜ∂‚óå"

window_rules:
- command: "move to workspace 2"
  match_process_name: "/Visual Studio Code|Code/"
- command: "move to workspace 3"
  match_process_name: "/Obsidian/"
- command: "move to workspace 4"
  match_process_name: "/thunderbird/"
- command: "move to workspace 5"
  match_process_name: "/Telegram|64gram|Signal|Discord/"
- command: "move to workspace 6"
  match_process_name: "/Spotify|MusicBee/"
- command: "move to workspace 8"
  match_process_name: "qBittorrent"
- command: "move to workspace 9"
  match_process_name: "/Steam|steamwebhelper/"

- command: "ignore"
  match_process_name: "/Taskmgr|ScreenClippingHost/Flow.Launcher/"

- command: "ignore"
  match_title: "[Pp]icture.in.[Pp]icture"
  match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

- command: "set floating"
  match_class_name: "#32770"

- command: "resize borders 0px -7px -7px -7px"
  match_process_name: "/steam|steamwebhelper/"

- command: "set width 25%"
  match_process_name: "thorium"
  match_title: "/ChatGPT/"

binding_modes:
- name: "resize"
  keybindings:
  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    bindings: ["H", "Left"]
  - command: "resize width +2%"
    bindings: ["L", "Right"]
  - command: "resize height +2%"
    bindings: ["K", "Up"]
  - command: "resize height -2%"
    bindings: ["J", "Down"]
  - command: "binding mode none"
    # Press enter/escape to return to default keybindings.
    bindings: ["Escape", "Enter"]

keybindings:
# Shift focus in a given direction.
- command: "focus left"
  bindings: ["Alt+H", "Alt+Left"]
- command: "focus right"
  bindings: ["Alt+L", "Alt+Right"]
- command: "focus up"
  bindings: ["Alt+K", "Alt+Up"]
- command: "focus down"
  bindings: ["Alt+J", "Alt+Down"]
- command: "exec 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'"
  bindings: ["Alt+OemPipe"]

# Move focused window in a given direction.
- command: "move left"
  bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
- command: "move right"
  bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
- command: "move up"
  bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
- command: "move down"
  bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

# Resize focused window by a percentage or pixel amount.
- command: "resize width -2%"
  binding: "Alt+U"
- command: "resize width +2%"
  binding: "Alt+P"
- command: "resize height +2%"
  binding: "Alt+O"
- command: "resize height -2%"
  binding: "Alt+I"

# As an alternative to the resize keybindings above, resize mode enables resizing via
# HJKL or arrow keys. The binding mode is defined above with the name "resize".
- command: "binding mode resize"
  binding: "Alt+R"

# Change tiling direction. This determines where new tiling windows will be inserted.
- command: "tiling direction toggle"
  binding: "Alt+V"

# Change focus between floating / tiling windows.
- command: "focus mode toggle"
  binding: "Alt+Space"

# Change the focused window to be floating / tiling.
- command: "toggle floating"
  binding: "Alt+Shift+Space"

# Change the focused window to be maximized / unmaximized.
- command: "toggle maximized"
  binding: "Alt+X"

# Minimize focused window.
- command: "set minimized"
  binding: "Alt+M"

# Close focused window.
- command: "close"
  binding: "Alt+Q"

# Kill GlazeWM process safely.
- command: "exit wm"
  binding: "Alt+Shift+E"

# Re-evaluate configuration file.
- command: "reload config"
  binding: "Alt+Shift+R"

# Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
# to start Windows Terminal and Git Bash respectively.
- command: "exec wt"
  binding: "Alt+Enter"

# Focus the workspace that last had focus.
- command: "focus workspace recent"
  binding: "Alt+B"

# Focus the next/previous workspace defined in `workspaces` config.
# - command: "focus workspace next"
#   binding: "Alt+T"
# - command: "focus workspace prev"
#   binding: "Alt+Shift+T"

# Change focus to a workspace defined in `workspaces` config.
- command: "focus workspace 1"
  binding: "Alt+1"
- command: "focus workspace 2"
  binding: "Alt+2"
- command: "focus workspace 3"
  binding: "Alt+3"
- command: "focus workspace 4"
  binding: "Alt+4"
- command: "focus workspace 5"
  binding: "Alt+5"
- command: "focus workspace 6"
  binding: "Alt+6"
- command: "focus workspace 7"
  binding: "Alt+7"
- command: "focus workspace 8"
  binding: "Alt+8"
- command: "focus workspace 9"
  binding: "Alt+9"

# # Move focused workspace to a monitor in a given direction.
# - command: "move workspace left"
#   binding: "Alt+A"
# - command: "move workspace right"
#   binding: "Alt+F"
# - command: "move workspace up"
#   binding: "Alt+D"
# - command: "move workspace down"
#   binding: "Alt+S"

# Move focused window to a workspace defined in `workspaces` config.
- commands: ["move to workspace 1", "focus workspace 1"]
  binding: "Alt+Shift+1"
- commands: ["move to workspace 2", "focus workspace 2"]
  binding: "Alt+Shift+2"
- commands: ["move to workspace 3", "focus workspace 3"]
  binding: "Alt+Shift+3"
- commands: ["move to workspace 4", "focus workspace 4"]
  binding: "Alt+Shift+4"
- commands: ["move to workspace 5", "focus workspace 5"]
  binding: "Alt+Shift+5"
- commands: ["move to workspace 6", "focus workspace 6"]
  binding: "Alt+Shift+6"
- commands: ["move to workspace 7", "focus workspace 7"]
  binding: "Alt+Shift+7"
- commands: ["move to workspace 8", "focus workspace 8"]
  binding: "Alt+Shift+8"
- commands: ["move to workspace 9", "focus workspace 9"]
  bindings: ["Alt+Shift+9"]
